# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: MyLocalAgent

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.13"
    displayName: "Use Python 3.13"

  - script: |
      cd backend
      pip install -r requirements.txt
    displayName: "Install backend dependencies"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/backend"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/backend.zip"
      replaceExistingArchive: true
    displayName: "Archive backend"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "Azure for Students"
      appType: "webAppLinux"
      appName: "research-compass-backend-anurag"
      package: "$(Build.ArtifactStagingDirectory)/backend.zip"
      runtimeStack: "PYTHON|3.13"
      startUpCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
      deploymentMethod: "zipDeploy"
      appSettings: "-SCM_DO_BUILD_DURING_DEPLOYMENT true -ENABLE_ORYX_BUILD true"
    displayName: "Deploy backend"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/frontend"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/frontend.zip"
      replaceExistingArchive: true
    displayName: "Archive frontend"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "Azure for Students"
      appType: "webAppLinux"
      appName: "research-compass-frontend-anurag"
      package: "$(Build.ArtifactStagingDirectory)/frontend.zip"
      runtimeStack: "PYTHON|3.13"
      startUpCommand: "python app.py"
      deploymentMethod: "zipDeploy"
      appSettings: "-SCM_DO_BUILD_DURING_DEPLOYMENT true -ENABLE_ORYX_BUILD true"
    displayName: "Deploy frontend"