# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: MyLocalAgent

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.13"
    displayName: "Use Python 3.13"

  - script: |
      cd backend
      pip install -r requirements.txt
    displayName: "Install backend dependencies"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/backend"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/backend.zip"
      replaceExistingArchive: true
    displayName: "Archive backend"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "Azure for Students"
      scriptType: "batch"
      scriptLocation: "inlineScript"
      inlineScript: |
        echo Stopping backend...
        az webapp stop --name research-compass-backend-anurag --resource-group research-compass-rg || echo ignoring stop error
        echo Waiting...
        ping 127.0.0.1 -n 11 > nul
        echo Deploying backend...
        az webapp deploy --name research-compass-backend-anurag --resource-group research-compass-rg --src-path "$(Build.ArtifactStagingDirectory)\backend.zip" --type zip
        echo Starting backend...
        az webapp start --name research-compass-backend-anurag --resource-group research-compass-rg || echo ignoring start error
        echo Backend done.
    displayName: "Deploy backend"

  - script: |
      cd frontend
      pip install -r requirements.txt
    displayName: "Install frontend dependencies"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/frontend"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/frontend.zip"
      replaceExistingArchive: true
    displayName: "Archive frontend"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "Azure for Students"
      scriptType: "batch"
      scriptLocation: "inlineScript"
      inlineScript: |
        echo Stopping frontend...
        az webapp stop --name research-compass-frontend-anurag --resource-group research-compass-rg || echo ignoring stop error
        echo Waiting...
        ping 127.0.0.1 -n 11 > nul
        echo Deploying frontend...
        az webapp deploy --name research-compass-frontend-anurag --resource-group research-compass-rg --src-path "$(Build.ArtifactStagingDirectory)\frontend.zip" --type zip
        echo Starting frontend...
        az webapp start --name research-compass-frontend-anurag --resource-group research-compass-rg || echo ignoring start error
        echo Frontend done.
    displayName: "Deploy frontend"